name: Testes de API

on:
  schedule:
    #crononograma de execução
    # 1º - minuto, 2º - hora,  3º - dia do mês, 4º - mês, 5º - dia da semana
    - cron: '0 0 * * *' # todo dia, à meia-noite


  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PORT: 3000
      BASE_URL: http://localhost:3000
      MONGODB_URI: mongodb://127.0.0.1:27017/gestao-de-alunos-test
      ADMIN_EMAIL: admin@escola.com
      ADMIN_SENHA: admin123

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci
      
      - name: Iniciar API
        run: |
          npm start > app.log 2>&1 &

      - name: Aguardar API iniciar
        run: |
          echo "Aguardando API iniciar..."

          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "API disponível!"
              exit 0
            fi

            echo "Tentativa $i/30..."
            sleep 2
          done

          echo "API não iniciou."
          echo "===== LOG DA API ====="
          cat app.log

          exit 1

      - name: Executar testes
        run: npm test

      - name: Salvar relatório de testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: reports/results.xml

      - name: Salvar log da API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-log
          path: app.log